RA-03: Completed 9 points
RomkaGra4/AndroidSprintApp pull request #1
Opened 2024-08-03 21:12 UTC by RomkaGra4

Доброго времени суток!)

Довольно тяжко дался материал. Перечитывал документацию и пересматривал лекции.
Готов к тому что будет "полно ошибок" которые нужно будет исправлять.

Буду признателен, если скажешь "где у меня какие косяки" чтобы я еще раз прошелся по ним и разобрался до конца))

2024-08-04 18:19 UTC, ievetrovdev requested changes

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/drawable/shape_rounded_variants.xml
> +<?xml version="1.0" encoding="utf-8"?>
это что и зачем?

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/drawable/icon.xml
это что за иконка? название неясное, применение тоже. объясни плз

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +    android:paddingTop="20dp"
Согласно ТЗ все значения размеров и других ресурсов необходимо выносить в соответствующие ресурсные файлы.

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +    android:background="#F4FAFF">
Про это тоже написано в ТЗ. Не нужно игнорировать

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="layout_marginStart">4px</dimen>
В андройд используются независимые от плотности экрана пиксели

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/values/themes.xml
> +    <style name="StyleNavButton" parent="Widget.Material3.Button">
Стили размещаются в файле со стилями

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/values/themes.xml
> +        <item name="android:windowLightStatusBar">true</item>
цвет статусбара так и не поменялся

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            app:icon="@drawable/ic_favorites"
Чтобы иконка не выглядела сплющенной необходимо выгружать ее вместе с фреймом. Предлагаю попробовать заменить

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            style="@style/StyleCategoriesButtom"/>
Для обеих кнопок достаточно одного стиля. Они отличаются только лишь цветом

2024-08-04 18:19 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            style="@style/StyleCategoriesButtom"/>
Форма не соответствует макету. Используй атрибут скругления углов

2024-08-15 19:58 UTC, RomkaGra4 commented on app/src/main/res/drawable/shape_rounded_variants.xml
> +<?xml version="1.0" encoding="utf-8"?>
Понял. Убрал

2024-08-16 09:39 UTC, RomkaGra4 commented on app/src/main/res/drawable/icon.xml
Если я не ошибаюсь, это иконка из первого урока где нужно было импортировать её с макета )

2024-08-16 10:05 UTC, RomkaGra4 commented on app/src/main/res/values/themes.xml
> +    <style name="StyleNavButton" parent="Widget.Material3.Button">
Запутался... Получается у нас файл с темами становится неактуальным, если все группируем в стилях?

2024-08-16 10:05 UTC, RomkaGra4 commented on app/src/main/res/values/themes.xml
> +    <style name="StyleNavButton" parent="Widget.Material3.Button">
P.S. отредактировал)

2024-08-16 10:08 UTC, RomkaGra4 commented on app/src/main/res/values/themes.xml
> +        <item name="android:windowLightStatusBar">true</item>
Так. Смотри, возможно плохо ищу. Но я так понимаю что в андроид нельзя установить цвет компонентов (значков) в статус баре, верно? Просто сам статус бар я окрасил, а значки могу делать либо белыми, либо черными... Хотя в фигме установлен цвет значков - #4D4D87. Можешь подсказать, изменить цвет возможно?) 
Если да - то не говори как. Я сам хочу разобраться :)

2024-08-16 10:19 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +    android:paddingTop="20dp"
Окей! Готов)

2024-08-16 10:20 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +    android:background="#F4FAFF">
Да да, как ты и выше писал - все значения пихаем в ресурсные файлы) Сделано!) Проверяй)

2024-08-16 11:14 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +            style="@style/StyleCategoriesButtom"/>
> Форма не соответствует макету. Используй атрибут скругления углов

Забыл установить закругленность углов. Сделано!
Только проблема - я не мог установить закругленность через стиль. Прописал в мейн_активити - @@drawable/shape_rounded_variants. И только тогда у меня и цвет подтягивался, и закругленность углов.

Подскажи, это считается за ошибку?

2024-08-16 11:15 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +            style="@style/StyleCategoriesButtom"/>
> Для обеих кнопок достаточно одного стиля. Они отличаются только лишь цветом

Касательно одного стиля не совсем понял. Кроме цвета у нас же есть "текст" и "расположение внутри LinearLayout. И у двух кнопок они разнятся...

2024-08-16 11:26 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +            app:icon="@drawable/ic_favorites"
Какой кайф когда получается :))) 
Готово)

2024-08-16 17:22 UTC, ievetrovdev commented on app/src/main/res/drawable/icon.xml
Это я понял. К тому и говорю – иконка же не применилась. 
Иконку приложения (именно которая будет отображаться на лаунчере, в настройках устройства и т.д.) экспортируем из фигмы как растровое изображение в png.

После этого согласно инструкции импортировать нужно как new image asset. В этом случае студия сгенерирует версии картинки в разных разрешениях в оригинале для разных случаев применения. Все они будут распределены по каталогам с соответствующими квалификаторами.

2024-08-16 17:29 UTC, ievetrovdev requested changes

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        <Button
не забывай всегда применять автоформатирование

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_width">match_parent</item>
ширина и высота это не стиль оформления – возвращаем обратно

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="backgroundTint">@color/сategoriesColor</item>
буквы на кириллице??

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:text">Категории</item>
все строки выносим в ресурсы

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtoms" parent="StyleTitle14">
Опечатка в слове

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">#FFFFFF</item>
в ресурсы

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
в ресурсы

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +    <style name="StyleFavoritesButtom" parent="StyleButtoms">
Названия стилей разные

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:orientation="horizontal"
theme тут не причем и к контейнеру никак не относится, убираем.

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:orientation="horizontal"
отсутствуют отступы по бокам согласно макету

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +    style="@style/StyleMainLayout">
тоже переборщил с оптимизацией. просто добавь правильный фон и все

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
lateinit - заманчивая конструкция, но опасная и никак не спасающая от NullPointerException. Вот тут Кирилл Розов наглядно объясняет почему лучше избежать использования lateinit по возможности. https://youtu.be/0nXXUzMyF8c

Лучше стараться продумать подходящее поведение по-умолчанию. В уроке я реализовывал backing property (резервное свойство). Но здесь предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-08-16 17:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:background="@drawable/shape_rounded_variants"
отдельную форму создавать не обязательно здесь. для кнопок достаточно задать в стили атрибут скругления углов напрямую и все заработает

2024-08-24 11:19 UTC, RomkaGra4 commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtoms" parent="StyleTitle14">
Пардон! Исправил)

2024-08-24 11:22 UTC, RomkaGra4 commented on app/src/main/res/values/styles.xml
> +        <item name="backgroundTint">@color/сategoriesColor</item>
Нет, опечатка была в слове) Исправил

2024-08-24 11:25 UTC, RomkaGra4 commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_width">match_parent</item>
Принято!

2024-08-24 11:34 UTC, RomkaGra4 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="layout_marginStart">4px</dimen>
Готово :)

2024-08-24 20:11 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +    style="@style/StyleMainLayout">
Окей. Делаю

2024-08-24 20:18 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +        android:orientation="horizontal"
Отступы по бокам согласно макету 16px - делаю

2024-08-24 20:26 UTC, RomkaGra4 commented on app/src/main/res/values/styles.xml
> +    <style name="StyleFavoritesButtom" parent="StyleButtoms">
Эм... все верно. Но ведь у нас меняется цвет, текст и отступы (у левой кнопки отступ слева и у правой кнопки отступ справа). Или я что-то не вкуриваю?)))

2024-08-24 20:31 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +            android:background="@drawable/shape_rounded_variants"
Решил пойти сложным путём зачем-то :)))

2024-08-24 20:47 UTC, RomkaGra4 commented on app/src/main/res/values/styles.xml
> +    <style name="StyleFavoritesButtom" parent="StyleButtoms">
Так, вроде дотумкал... только теперь получается что в активити_мейн в кнопках много параметров. 
Я думал тут смысл все максимально раскидать - стиль, цвета, строки (ресурсы).

2024-08-25 09:56 UTC, ievetrovdev commented
Предлагаю тебе не резолвить треды обсуждений здесь, а то мне все равно приходится все раскрывать при повторной проверке, чтобы входить в контекст)

2024-08-25 14:32 UTC, ievetrovdev requested changes

2024-08-25 14:32 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/MainActivity.kt
> -    override fun onCreate(savedInstanceState: Bundle?) {
Удалил метод жизненного цикла onCreate в котором происходит создание экрана. Недостаточно внимательно смотрел уроки про ViewBinding или вообще не смотрел – на экране ничего не отображается, так не пойдет.

2024-08-25 14:32 UTC, ievetrovdev commented on app/src/main/res/drawable/shape_rounded_variants.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android">
Этот файл можно удалять за ненадобностью

2024-08-25 14:32 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="6dp"
Не обязательно для каждой стороны прописывать марджины по отдельности. Есть более универсальные атрибуты. 
android:layout_margin=""
android:layout_marginHorizontal=""
android:layout_marginVertical=""

2024-08-25 14:32 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +
две пустые строки подряд обычно не оставляем

2024-08-25 14:32 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="layoutColor">#F4FAFF</color>
Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-08-25 14:32 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="layout_marginEnd">4dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-08-25 14:32 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="cornerRadius">8px</item>
В Android используются независимые от плотности экрана пиксели.

2024-08-25 14:32 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="6dp"
И после уточнения конкретного значения отступа по макету не забудь что вообще все размеры выносим в ресурсы

2024-08-29 23:13 UTC, ievetrovdev approved these changes

2024-08-29 23:13 UTC, ievetrovdev commented on app/build.gradle.kts
> +    buildFeatures{
апрув, всё поправил

2024-08-29 23:13 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:paddingVertical">8dp</item>
ресурсы!

2024-08-29 23:13 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:paddingHorizontal">16dp</item>
ресурсы

2024-08-29 23:13 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="cornerRadius">8dp</item>
ресурсы

2024-09-06 17:31 UTC, merged