RA-04: Сompleted 5 points
RomkaGra4/AndroidSprintApp pull request #2
Opened 2024-09-11 18:22 UTC by RomkaGra4

2024-09-12 20:13 UTC, ievetrovdev requested changes

2024-09-12 20:13 UTC, ievetrovdev commented on app/build.gradle.kts
> +    implementation("androidx.fragment:fragment-ktx:$fragment_version")
Обрати внимание, что все остальные библиотеки расположены в toml файле. Давай и эту либу тоже поместим туда, а обращаться будем по аналогии по ссылке.

Подробнее про новый формат хранения списка библиотек рассказываю вот тут (таймкод): https://youtu.be/bL6RQ2E729o?si=GnvTzQFjblBY7UPU&t=441

2024-09-12 20:13 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/MainActivity.kt
> +        fragmentTransaction.replace(R.id.mainContainer, categoriesListFragment)
Ты используешь Java метод add/replace из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add() из класса FragmentTransaction.kt. 

Именно для импорта метода add/replace нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

И предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). То есть вся магия должна происходить в одной лямбде.

2024-09-12 20:13 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="category_fragment">fragment_list_categories.xml</string>
Этот текст-заглушка не требует сохранения в ресурсах, он все равно не будет подвержен локализации. Поэтому как временное решение можно просто захардкодить название фрагмента.

2024-09-12 20:13 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="navigation_bar_padding_vertical">8dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-09-12 20:13 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="l_margin_start_and_end_category_fragment">16dp</dimen>
повтор

2024-09-12 20:13 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="@dimen/l_margin_top_category_fragment"
А зачем тут отступ сверху

2024-09-13 08:32 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="@dimen/l_margin_top_category_fragment"
Так ведь если я правильно понял данный фрагмент занимает часть экрана от середины до кнопок.
А сверху уже другой элемент идет... Или это все единый фрагмент?

2024-09-13 20:27 UTC, ievetrovdev requested changes

2024-09-13 20:27 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/CategoriesListFragment.kt
> +        return binding!!.root
!! – оператор-утверждение "это не null" . Как я упоминал ранее – это опасный оператор и не рекомендуется его использовать, тк если в переменную все же придет null – приложение крашнется.

Это отрицательно повлияет на пользовательский опыт и сразу без дебага будет сложно найти причину вылета приложения. Устройств на андройд (и версий андройд) множество, далеко не все работают идеально, как наши собственные или эмулятор. Поэтому, чтобы меньше было проблем в будущем, подкладываем солому заранее. А именно добавляя разные безопасные обработчики.

В уроке я реализовывал backing property (резервное свойство). Попробуй его внедрить тоже

2024-09-13 20:27 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/CategoriesListFragment.kt
> +    }
Поскольку жизненный цикл фрагмента длиннее, чем у view внутри него, рекомендуется очищать binding в методе onDestroyView.
Подробнее можно почитать здесь: https://developer.android.com/topic/libraries/view-binding#fragments

2024-09-13 20:27 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/MainActivity.kt
> +        supportFragmentManager.commit {
Молодец, что решил использовать новую реализацию через commit{}

2024-09-13 20:27 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
>      android:paddingTop="2dp">
Этот параметр выглядит здесь странно. Почему решил его добавить?

2024-09-13 20:27 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        style="@style/StyleCategoriesFragment"
Не понимаю, какой смысл несет этот стиль и зачем в нем стоят magrin'ы. Можешь написать? 
Сам по себе контейнер может менять фрагменты внутри себя, присваивать ему имя StyleCategoriesFragment неправильно,

Если этот стиль действительно нужен, то точно нейминг лучше поменять

2024-09-14 17:20 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
>      android:paddingTop="2dp">
я че-то проверяю и сам не помню почему я его сюда поставил...

2024-09-14 17:28 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +        style="@style/StyleCategoriesFragment"
Вань, у меня на самом деле крышак едет по теме стилей :)) 
Я не совсем осознаю в каких случаях их можно делать а в каких нет))

Просто до этого ты писал _"Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили."_

До этого у меня magrin'ы были указаны просто в activity_main.xml (т.е. никакого стиля не было).
Поскольку у меня дублировались одни и те же значения с разными айди, ты говорил мне от этого уходить.

Мне как "тугодуму" можешь пожалуйста подсказать чтобы я уже не топтался на этой теме а пошел вперед:
"вот я убрал стиль, добавил сейчас марджины в activity_main.xml и указал туда 16dp. Это же не правильно, так? Ведь я подобное должен сразу отправлять в ресурсы? Если да - то как я должен добавлять в ресурсы если у меня одни и те же значения с разными айди? Получается я должен эти значения как то назвать чтобы было понятно что они относятся и к фрагменту и к navigation_bar_padding (как к примеру у меня указано в проекте)?" 

Буду очень признателен если подскажешь. Чтобы я этот момент проработал.
Потому что я меж 3-х деревьев гуляю :)))

2024-09-15 11:31 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/CategoriesListFragment.kt
> +    private val binding get() = _binding!!
Реализовал, как в ролике, но не до конца)
Тут продолжение с объяснением
https://youtu.be/ABoZGM6N3mE?t=542

2024-09-15 11:31 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="l_margin_top_category_fragment">272dp</dimen>
параметр нигде не используется

2024-09-15 11:31 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        style="@style/StyleCategoriesFragment"
Хороший тон использовать в вёрстки только параметры из ресурсов. Если у тебя какая-то величина в dimens начинает использоваться для разных целей, то просто переименуй её в более нейтральное название, по типу main_space_16, и используй уже в стилях. Удобнее всего это сделать через Shift+F6 в студии. 
В целом твоя цепочка размышлений была верна)

2024-09-15 11:35 UTC, ievetrovdev requested changes

2024-09-15 11:35 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
>          <item name="cornerRadius">8dp</item>
это бы тоже вынести в ресурсы

2024-09-15 11:35 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Здесь больше вопрос зачем тебе во FragmentContainerView эти марджины в целом?

2024-09-15 11:38 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Если глянуть на макет, то у твоего места для фрагментов появились отступы слева и справа, все фрагменты внутри не будут занимать весь экран по ширине. Щас это может не очевидно, можешь оставить их до следующего ПР. Там уже будет наглядно видно в чем проблема
![image](https://github.com/user-attachments/assets/6f28a79f-6522-4844-853a-01ecd7d957ce)

2024-09-17 18:25 UTC, RomkaGra4 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="l_margin_top_category_fragment">272dp</dimen>
используется в StyleNavButton же) 
Который в LinearLayout с кнопками)

2024-09-17 18:29 UTC, RomkaGra4 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Мне показалось что по макету там отступы стоят. Поэтому я их установил.
Ну давай оставим до следующего ПР, и если что я сам увижу косяк и тогда уберу их

2024-09-18 18:18 UTC, ievetrovdev approved these changes
Сейчас всё корректно, молодец! Приступай к следующему заданию

2024-09-18 18:28 UTC, merged