RA-06: Completed tasks in №06
RomkaGra4/AndroidSprintApp pull request #4
Opened 2024-09-27 19:10 UTC by RomkaGra4

2024-09-28 20:01 UTC, ievetrovdev requested changes

2024-09-28 20:01 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/Recipe.kt
> +    val ingredients:List<Ingredient>
Глянь внимательнее файл рецептов json, там еще несколько полей

2024-09-28 20:01 UTC, ievetrovdev commented on app/build.gradle.kts
> +                srcDirs("src\\main\\assets", "src\\main\\assets")
Это прописывать вовсе не нужно, для ассетов это уже зарезервированный путь, он автоматически распознается гредлом

2024-09-28 20:01 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/recipes.kt
> +
От таких лишних переходов на новую строку лучше избавлятся, это повысит читаемость кода

2024-09-28 20:01 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/recipes.kt
> +    fun getCategories(): List<com.example.androidsprintapp.Category> {
Мы импортируем класссы в файл через import, напрямую обращаться к пути файла крайне не рекомендуется, усложняет читаемость кола

2024-09-29 17:06 UTC, RomkaGra4 commented on app/src/main/java/com/example/androidsprintapp/recipes.kt
> +
Ты имеешь ввиду "пустые строки", верно? 

P.S. Прости) Я помню ты писал чтобы я не делал много комментов)) Но тут я просто слегка непонял)

2024-09-30 09:35 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/recipes.kt
> +
Да, я про пустые строки)

2024-09-30 09:36 UTC, ievetrovdev approved these changes
Теперь всё верно! Молодец

2024-10-01 14:38 UTC, merged