RA-07: Completed tasks in №07
RomkaGra4/AndroidSprintApp pull request #5
Opened 2024-10-03 19:24 UTC by RomkaGra4

2024-10-04 15:20 UTC, ievetrovdev requested changes

2024-10-04 15:20 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +        tools:listitem="@layout/item_category" />
Ты добавил tools:listitem="@layout/item_category". Теперь на превьюхе в студии видны карточки категории и как они будут выглядеть в приложении.

Карточку надо сверстать. Представь, что элемент списка – это вот весь данный лейаут. Сделай для него верстку, заполни тестовыми данными в качестве картинки, названия и описания через атрибуты tools.

2024-10-04 15:20 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +            android:src="@drawable/bcg_categories"
Не забудь добавить “описание контента”. contentDescription используется для предоставления текстового описания для не текстовых элементов, таких как изображения, кнопки с иконками и других графических объектов.

2024-10-04 15:20 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:layout_height="224dp">
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-10-04 15:20 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +    <style name="ShapeDrawable">
Название не очень информативное, в нём же содержится текст, дополни по типу ShapedTextDrawable

2024-10-06 19:31 UTC, RomkaGra4 commented on app/src/main/res/layout/fragment_favorites.xml
> +        tools:listitem="@layout/item_category" />
Правильно я понял, что мне нужно сверстать только ОДНУ карточку и уже потом на этом шаблоне мы будем делать те что требуются согласно Figma ? 

Надеюсь я правильно понял задание :))

2024-10-06 19:39 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +        tools:listitem="@layout/item_category" />
Да, мы создаем шаблон с тестовыми значениями, чтоб просто увидеть как это будет отображаться. Потом мы будем передавать уже разные значения в набор карточек, а она будет их отображать

2024-10-06 19:51 UTC, ievetrovdev requested changes

2024-10-06 19:51 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:text="Заголовок"
Для тестовых значений, которые будут отображаться только на макетах, не в реальном приложении, существует tools:. Весь тестовый текст нужно вынести в тулс

2024-10-06 19:51 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="@dimen/category_image_height" />
Добавить также тестовое фото через tools:

2024-10-06 19:51 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:textSize="14sp" />
Все такие значения мы выносим в ресурсы

2024-10-06 19:51 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="category_name_height">16dp</dimen>
Текст должен быть не константой, если строка станет длинее то всё поломается. Ширина и длина текста должна быть по контенту, это прописано в задании

2024-10-06 19:51 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
В задании пописано, что мы делаем не для fragment_favorites вёрстку, а для fragment_categories

2024-10-06 19:51 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +        tools:itemCount="2"
Сделай количество штук 6, они должны выглядеть как на макете из фигрмы, хоть и с одинаковыми данными. Сейчас 1 элемент занимает весь столб по динне

2024-10-06 19:51 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +        android:layout_width="@dimen/category_item_width"
Ширина должна быть по контенту

2024-10-06 19:51 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    android:layout_width="match_parent"
Ширина должна быть по контенту

2024-10-07 11:57 UTC, RomkaGra4 commented on app/src/main/res/layout/fragment_favorites.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Подожди? Получается в fragment_list_categories или именно в fragment_categories ? 
Просто у нас нет fragment_categories. Значит должны создать?

2024-10-08 08:37 UTC, ievetrovdev commented
Про tools: ты неправильно понял.
Чтобы увидеть текст на макете в студии, ты должен использовать tools:text, tools:src методы. Это отдельное пространство имён, в основном мы используемм пространства android:, app:. 
Пространстве имен android: используется для указания атрибутов, которые будут применяться во время выполнения (runtime) приложения на устройстве.

Пространстве имен tools:  используется только в среде разработки  в Android Studio и не влияет на поведение приложения на реальном устройстве. Эти атрибуты предназначены для удобства отображения в редакторе макетов, чтобы разработчики могли видеть предварительный результат без необходимости запускать приложение.

Проверить что всё корректно можно тем, что на макете в студии будет этот текст или фото

Подробнее можешь почитать в доке здесь про tools
https://developer.android.com/studio/write/tool-attributes

2024-10-11 16:57 UTC, ievetrovdev commented on app/src/main/java/com/example/androidsprintapp/recipes.kt
> +        Category(0, "Бургеры", "Рецепты всех популярных видов бургеров", "drawable/burger.png"),
Здесь мы ничего не трогаем, эти значения константные

2024-10-11 16:57 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Мы к CategoriesListFragment уже подключили fragment_list_categories в прошлых заданиях. Про  fragment_favorites ничего нет в задании
<img width="912" alt="Снимок экрана 2024-10-11 в 19 55 47" src="https://github.com/user-attachments/assets/f0b26df2-a209-450c-af08-5df138b6825f">

2024-10-11 17:04 UTC, ievetrovdev commented
Посмотри, как твой макет выглядит в студии. Твои два элемента занимают весь список, должно соотвествовать макету из фигмы.
Установи в item_cateogry всем элементам ширину по родителю (match_parent), длину фото пропиши по дизайну из фигмы, длину текста - по контенту.

![image](https://github.com/user-attachments/assets/c1f37d82-00c5-45ef-8439-3d1dfce6458e)

2024-10-17 18:09 UTC, Churickoid requested changes

2024-10-17 18:09 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="@dimen/item_category_image_height"
Сейчас фото занимает не всю ширину карточку, добавь android:scaleType="centerCrop"

2024-10-17 18:09 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +    android:layout_height="wrap_content"
Сделай макет фрагмента шире,  твои карточки будут занимать не все пространство. Сделай их по ширине match_parent.  
Также отсутсвуют отступы между элементами, добавь в  cardView марджины по дизайну

2024-10-17 18:09 UTC, aGroupoid commented on app/src/main/res/layout/fragment_favorites.xml
>      tools:context=".FavoritesFragment">
Мы делаем макет для fragment_list_category, это в задании прописано.

2024-10-17 18:09 UTC, Churickoid commented on app/src/main/res/values/strings.xml
>      <string name="hello_blank_fragment">Hello blank fragment</string>
Тестовая строка, её нужно убрать из макета

2024-10-18 13:02 UTC, RomkaGra4 commented on app/src/main/res/layout/item_category.xml
> +    android:layout_height="wrap_content"
Смотри, сделал как ты указал. Только теперь у меня от картинки еще остается пространство пустое на фрагменте. Т.е. картинка не занимает всю часть в item_category. Соответственно это видно в fragment_favorites

2024-10-18 17:27 UTC, Churickoid commented
> Смотри, сделал как ты указал. Только теперь у меня от картинки еще остается пространство пустое на фрагменте. Т.е. картинка не занимает всю часть в item_category. Соответственно это видно в fragment_favorites

Картинке тоже надо был указать match_parent по ширине) Весь элемент должен корректно отрисовываться на любой ширине

2024-10-18 17:31 UTC, Churickoid commented
Поправь эту проблему уже. Мы щас делаем экран списка категорий, а не избранного. Переименую fragment_favorites во fragment_list_categories. На этом макете список категорий 
<img width="657" alt="Снимок экрана 2024-10-18 в 20 29 05" src="https://github.com/user-attachments/assets/c5174d88-fa8f-468d-bcb2-fa84b23b3b04">

2024-10-18 17:36 UTC, Churickoid commented
Не хватает padding для cardView, у тебя все элементы в плотную прижаты, глянь какие отсутпы на макете фигмы 
https://www.figma.com/design/89K5JomHGyIkUFUaBKRBXi/RecipesApp-%5BAndroidSprint%5D?node-id=0-1&node-type=canvas&t=dIO0OCrz0cQf4KeN-0
<img width="307" alt="Снимок экрана 2024-10-18 в 20 33 18" src="https://github.com/user-attachments/assets/3b602d5d-e3b3-4018-94a1-ea3ed5f7ae80">

2024-10-19 10:07 UTC, RomkaGra4 commented
По поводу fragment_favorites и fragment_list_categories я чето максимально туплю :)) Сори!) 

Касательно  padding для cardView: я сделал через margin; padding не помогал. В целом норм? Или именно padding нужен?)

2024-10-19 12:27 UTC, Churickoid requested changes
Да, всё верно! Молодец! По поводу padding опечатлся, да, только magrin в твоей ситуации нужен. Один некретичный коммент на удержании остался, не отправился. Поправь его уже в следующем задании

2024-10-19 12:27 UTC, aGroupoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_marginStart="@dimen/default_spacing_8"
Текст будет прижиматься к правому краю, не хватает отступа со второй стороны. Пропиши marginHorizontal

2024-10-19 12:28 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_marginStart="@dimen/default_spacing_8"
для двух текстов в item_category

2024-10-20 07:56 UTC, merged